# Header
menu:
  首頁: /
  過往: /archives
  摯友: /friends
  訂閱: /atom.xml
  關於: /about

sitemap:
    path: sitemap.xml

# Content
excerpt_link: 閱讀全文
fancybox: true

# Sidebar
widgets:
- tag

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
github:
weibo:
